#!/usr/bin/python

import sys


f = open(sys.argv[1])
text = f.read()
lines = text.split('\n')
for i in range(0, len(lines)):
  if len(lines[i]) > 75:
    print(str(i) + ' length ' + str(len(lines[i])))
  words = lines[i].split()
  for a in words:
    try:
      x = int(a)
      theSet = set(words)
      if 'int' not in theSet and 'double' not in theSet and 'boolean' not in theSet and 'String' not in theSet:
        print('Magic Number at line ' + i)
    except:
      x = 'a ok'   
    

